# Generated by Django 4.0.6 on 2022-07-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('token_id', models.IntegerField()),
                ('file_url', models.CharField(max_length=500)),
                ('metadata_url', models.CharField(max_length=500)),
                ('is_live', models.BooleanField()),
            ],
        ),
    ]
