# Generated by Django 4.0.6 on 2022-07-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin_issuer_nft_is_verified_nft_issuer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='password',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='username',
            new_name='added_by',
        ),
        migrations.AddField(
            model_name='admin',
            name='designation',
            field=models.CharField(default='Developer', max_length=50),
        ),
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(default='BIT', max_length=50),
        ),
    ]
