# Generated by Django 4.0.6 on 2022-07-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_password_admin_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuer',
            old_name='owner',
            new_name='account',
        ),
        migrations.AddField(
            model_name='issuer',
            name='added_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
