# Generated by Django 4.0.6 on 2022-07-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_owner_issuer_account_issuer_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='contract_address',
            field=models.CharField(default='0x129ddf010BeAAE0642DBd72fc9f30ad90e2dfB7b', max_length=50),
        ),
    ]
