# Generated by Django 4.0.6 on 2022-07-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_issuer_contract_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('added_by', models.CharField(max_length=50)),
                ('contract_address', models.CharField(max_length=50)),
                ('frame', models.FileField(upload_to='')),
            ],
        ),
    ]
