# Generated by Django 4.0.6 on 2022-07-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='frame',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='added_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='contract_address',
            field=models.CharField(max_length=50),
        ),
    ]
