# Generated by Django 4.0.6 on 2022-07-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_destination_frame_alter_issuer_added_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='kpi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_certificates', models.IntegerField()),
            ],
        ),
    ]
