# Generated by Django 4.0.6 on 2022-07-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='total_certificates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuer',
            name='total_certificates',
            field=models.IntegerField(default=0),
        ),
    ]
