# Generated by Django 4.0.6 on 2022-07-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_destination_total_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='only_certificates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='only_souvenirs',
            field=models.IntegerField(default=0),
        ),
    ]
