# Generated by Django 4.0.6 on 2022-08-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_kpi_only_certificates_kpi_only_souvenirs'),
    ]

    operations = [
        migrations.CreateModel(
            name='individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('storage_used', models.FloatField()),
                ('storage_limit', models.FloatField()),
            ],
        ),
    ]
